version: "3.2"
services:
  master:
    build: .
    environment: &environment
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pingmon
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=
      - PUMA_THREADS=50
      - WEB_PORT=8080
      - WEB_HOST=0.0.0.0
      - WS_HOST=0.0.0.0
      - MASTER_HOST=master
      - MASTER_PORT=8081
      - BUNDLE_PATH=/bundle_cache
      - APP_ENV=development
    volumes:
      - .:/pingmon
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.ash_history
      - ~/.gitconfig:/root/.gitconfig
      - bundle_cache:/bundle_cache
    depends_on:
      - db
    networks:
      - default
      - private_network
    ports:
      - "8080:8080"
    expose:
      - "8081"
    logging: &logging
      options:
        max-size: "1m"
        max-file: "1"
    command: sh -c "foreman start master"
  worker:
    build: .
    environment: *environment
    networks:
      - private_network
    depends_on:
      - db
      - master
    logging: *logging
    command: sh -c "foreman start worker"
  db:
    image: postgres:9.5-alpine
    environment: *environment
    networks:
      - private_network
    logging: *logging
  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache
volumes:
  bundle_cache:

networks:
  private_network:
    internal: true

